name: directionality
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - scikit-image
  - pandas
  - scikit-image
  - matplotlib
  - ipykernel
  - imagecodecs
  - pip  # ensure pip is available for pip installs
  - pip:
      - scikit-image @ git+https://github.com/Klest94/scikit-image-fork.git@v0.25-no-hog-normalization
