name: directionality
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - pandas
  - scikit-image>=0.23,<0.26
  - matplotlib
  - ipykernel
  - imagecodecs
#  - pip
#  - pip:
#      - scikit-image @ git+https://github.com/Klest94/scikit-image-fork.git@v0.25-hogpatch
